# Generated by Django 5.2 on 2025-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Physician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("MD", "Doctor of Medicine (M.D.)"),
                            ("DO", "Doctor of Osteopathic Medicine (D.O.)"),
                            ("NP", "Nurse Practitioner (N.P.)"),
                            ("PA", "Physician Assistant (P.A.)"),
                            ("DC", "Doctor of Chiropractic (D.C.)"),
                            ("DDS", "Doctor of Dental Surgery (D.D.S.)"),
                            ("DMD", "Doctor of Medicine in Dentistry (D.M.D.)"),
                            ("PhD", "Doctor of Philosophy (Ph.D.)"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
