# Generated by Django 5.2 on 2025-04-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Separated", "Separated"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                            ("Prefer not to answer", "Prefer not to answer"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ssn", models.CharField(max_length=11, unique=True)),
                ("address", models.TextField()),
                ("address_2", models.TextField(blank=True, null=True)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices="(('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'))",
                        max_length=50,
                    ),
                ),
                ("zip_code", models.CharField(max_length=10)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("pcp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Brazilian Portuguese", "Brazilian Portuguese"),
                            ("French", "French"),
                            ("German", "German"),
                            ("Italian", "Italian"),
                            ("Japanese", "Japanese"),
                            ("Korean", "Korean"),
                            ("Portuguese", "Portuguese"),
                            ("Russian", "Russian"),
                            ("Simplified Chinese", "Simplified Chinese"),
                            ("Spanish", "Spanish"),
                            ("Traditional Chinese", "Traditional Chinese"),
                            ("United States English", "United States English"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        choices=[
                            ("Hispanic and Latino", "Hispanic and Latino"),
                            ("Not Hispanic and Latino", "Not Hispanic and Latino"),
                        ],
                        max_length=50,
                    ),
                ),
                ("patient_consent", models.BooleanField(default=True)),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("Primary", "Primary"),
                            ("Secondary", "Secondary"),
                            ("Tertiary", "Tertiary"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("insurance_id", models.CharField(max_length=100, unique=True)),
                ("group_number", models.CharField(max_length=100)),
                ("date_of_service", models.DateField()),
                ("plan_number", models.CharField(max_length=255, unique=True)),
                (
                    "co_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("eligibility_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("payer_phone", models.CharField(max_length=20)),
                ("payer_fax", models.CharField(max_length=20)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Self", "Self"),
                            ("Spouse", "Spouse"),
                            ("Child", "Child"),
                            ("Mother", "Mother"),
                            ("Father", "Father"),
                            ("Grandparent", "Grandparent"),
                            ("Grandchild", "Grandchild"),
                            ("Niece/Nephew", "Niece/Nephew"),
                            ("Stepchild", "Stepchild"),
                            ("Fosterchild", "Fosterchild"),
                            ("Ward", "Ward"),
                            ("Employee", "Employee"),
                            ("Life Partner", "Life Partner"),
                            ("Significant Other", "Significant Other"),
                            ("Handicapped Dependent", "Handicapped Dependent"),
                            ("Other", "Other"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "ref_physician",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="api.physician",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="api.servicetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AllergyNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.patient"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AllergyTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allergen", models.CharField(max_length=255)),
                ("reaction", models.CharField(max_length=50)),
                ("vial_name", models.CharField(blank=True, max_length=100, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("diagnosis", models.JSONField(blank=True, default=list)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.patient"
                    ),
                ),
            ],
            options={
                "unique_together": {("patient", "allergen")},
            },
        ),
    ]
