# Generated by Django 5.2 on 2025-04-29 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_patient_state"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="allergytest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="allergytest",
            name="patient",
        ),
        migrations.AlterField(
            model_name="patient",
            name="state",
            field=models.CharField(
                choices="(('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'))",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AllergyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dose", models.CharField(max_length=50)),
                ("date", models.DateField()),
                (
                    "arm",
                    models.CharField(
                        choices=[("L", "Left"), ("R", "Right")], max_length=1
                    ),
                ),
                ("peak_flow", models.CharField(max_length=50)),
                ("tech_id", models.CharField(max_length=50)),
                ("hcrm_applied", models.BooleanField(default=False)),
                (
                    "reaction",
                    models.CharField(
                        choices=[
                            ("MR", "MR"),
                            ("NR", "NR"),
                            ("3mm", "3mm"),
                            ("4mm", "4mm"),
                            ("5mm", "5mm"),
                            ("6mm", "6mm"),
                            ("7mm", "7mm"),
                            ("8mm", "8mm"),
                            ("9mm", "9mm"),
                            ("10mm", "10mm"),
                            (">10mm", ">10mm"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "vial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="api.vial",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="AllergyNotes",
        ),
        migrations.DeleteModel(
            name="AllergyTest",
        ),
    ]
