from django.core.management.base import BaseCommand
from datetime import date
from api.models import Patient, Physician, ServiceType


class Command(BaseCommand):
    help = "Create test patients for development"

    def handle(self, *args, **kwargs):
        try:
            ref_physician = Physician.objects.get(id=1)
        except Physician.DoesNotExist:
            self.stdout.write(self.style.ERROR("Physician with ID 1 does not exist."))
            return

        service_type = ServiceType.objects.first()

        patients_data = [
            {
                "first_name": "John",
                "middle_name": "A",
                "last_name": "Doe",
                "birth_date": date(1990, 1, 1),
                "gender": "Male",
                "email": "john@example.com",
                "marital_status": "Single",
                "ssn": "123-45-6789",
                "address": "123 Elm St",
                "city": "New York",
                "state": "NY",
                "zip_code": "10001",
                "phone": "555-111-2222",
                "language": "English",
                "ethnicity": "Caucasian",
                "insurance_type": "Private",
                "insurance_id": "INS123456",
                "group_number": "GRP001",
                "date_of_service": date.today(),
                "plan_number": "PLAN001",
                "payer_phone": "555-999-9999",
                "payer_fax": "555-999-8888",
                "relationship": "Self",
            },
            {
                "first_name": "Jane",
                "middle_name": "B",
                "last_name": "Smith",
                "birth_date": date(1985, 5, 5),
                "gender": "Female",
                "email": "jane@example.com",
                "marital_status": "Married",
                "ssn": "987-65-4321",
                "address": "456 Oak St",
                "city": "Chicago",
                "state": "IL",
                "zip_code": "60601",
                "phone": "555-222-3333",
                "language": "Spanish",
                "ethnicity": "Hispanic",
                "insurance_type": "Medicare",
                "insurance_id": "INS654321",
                "group_number": "GRP002",
                "date_of_service": date.today(),
                "plan_number": "PLAN002",
                "payer_phone": "555-123-4567",
                "payer_fax": "555-123-4568",
                "relationship": "Spouse",
            },
            {
                "first_name": "Alice",
                "middle_name": "C",
                "last_name": "Johnson",
                "birth_date": date(1995, 3, 10),
                "gender": "Female",
                "email": "alice.j@example.com",
                "marital_status": "Single",
                "ssn": "555-66-7777",
                "address": "789 Maple Ave",
                "city": "Seattle",
                "state": "WA",
                "zip_code": "98101",
                "phone": "555-333-4444",
                "language": "English",
                "ethnicity": "Asian",
                "insurance_type": "Private",
                "insurance_id": "INS789012",
                "group_number": "GRP003",
                "date_of_service": date.today(),
                "plan_number": "PLAN003",
                "payer_phone": "555-111-2223",
                "payer_fax": "555-111-2224",
                "relationship": "Child",
            },
            {
                "first_name": "Robert",
                "middle_name": "D",
                "last_name": "Williams",
                "birth_date": date(1970, 12, 22),
                "gender": "Male",
                "email": "robert.w@example.com",
                "marital_status": "Married",
                "ssn": "999-88-7777",
                "address": "321 Pine Rd",
                "city": "Austin",
                "state": "TX",
                "zip_code": "73301",
                "phone": "555-444-5555",
                "language": "English",
                "ethnicity": "African American",
                "insurance_type": "Medicaid",
                "insurance_id": "INS999888",
                "group_number": "GRP004",
                "date_of_service": date.today(),
                "plan_number": "PLAN004",
                "payer_phone": "555-555-1234",
                "payer_fax": "555-555-4321",
                "relationship": "Parent",
            },
            {
                "first_name": "Emily",
                "middle_name": "E",
                "last_name": "Davis",
                "birth_date": date(2000, 6, 18),
                "gender": "Female",
                "email": "emily.d@example.com",
                "marital_status": "Single",
                "ssn": "101-11-2020",
                "address": "910 Cedar Blvd",
                "city": "Phoenix",
                "state": "AZ",
                "zip_code": "85001",
                "phone": "555-555-6666",
                "language": "English",
                "ethnicity": "Native American",
                "insurance_type": "Private",
                "insurance_id": "INS101202",
                "group_number": "GRP005",
                "date_of_service": date.today(),
                "plan_number": "PLAN005",
                "payer_phone": "555-321-9876",
                "payer_fax": "555-321-9877",
                "relationship": "Other",
            },
            {
                "first_name": "David",
                "middle_name": "F",
                "last_name": "Martinez",
                "birth_date": date(1982, 11, 30),
                "gender": "Male",
                "email": "david.m@example.com",
                "marital_status": "Married",
                "ssn": "303-22-3033",
                "address": "204 Spruce St",
                "city": "Miami",
                "state": "FL",
                "zip_code": "33101",
                "phone": "555-666-7777",
                "language": "Spanish",
                "ethnicity": "Hispanic",
                "insurance_type": "Medicare",
                "insurance_id": "INS303303",
                "group_number": "GRP006",
                "date_of_service": date.today(),
                "plan_number": "PLAN006",
                "payer_phone": "555-765-4321",
                "payer_fax": "555-765-1234",
                "relationship": "Self",
            },
            {
                "first_name": "Sophia",
                "middle_name": "G",
                "last_name": "Lee",
                "birth_date": date(1999, 8, 15),
                "gender": "Female",
                "email": "sophia.lee@example.com",
                "marital_status": "Single",
                "ssn": "505-33-5055",
                "address": "800 Willow Dr",
                "city": "Los Angeles",
                "state": "CA",
                "zip_code": "90001",
                "phone": "555-777-8888",
                "language": "Korean",
                "ethnicity": "Asian",
                "insurance_type": "Private",
                "insurance_id": "INS505505",
                "group_number": "GRP007",
                "date_of_service": date.today(),
                "plan_number": "PLAN007",
                "payer_phone": "555-234-5678",
                "payer_fax": "555-234-8765",
                "relationship": "Self",
            },
            {
                "first_name": "Michael",
                "middle_name": "H",
                "last_name": "Brown",
                "birth_date": date(1978, 7, 9),
                "gender": "Male",
                "email": "michael.b@example.com",
                "marital_status": "Married",
                "ssn": "606-44-6066",
                "address": "72 Birch Ln",
                "city": "Denver",
                "state": "CO",
                "zip_code": "80201",
                "phone": "555-888-9999",
                "language": "English",
                "ethnicity": "Caucasian",
                "insurance_type": "Private",
                "insurance_id": "INS606606",
                "group_number": "GRP008",
                "date_of_service": date.today(),
                "plan_number": "PLAN008",
                "payer_phone": "555-876-5432",
                "payer_fax": "555-876-4321",
                "relationship": "Spouse",
            },
            {
                "first_name": "Liam",
                "middle_name": "I",
                "last_name": "Nguyen",
                "birth_date": date(2002, 9, 25),
                "gender": "Male",
                "email": "liam.ng@example.com",
                "marital_status": "Single",
                "ssn": "707-55-7077",
                "address": "99 River Rd",
                "city": "San Diego",
                "state": "CA",
                "zip_code": "92101",
                "phone": "555-999-0000",
                "language": "Vietnamese",
                "ethnicity": "Asian",
                "insurance_type": "Medicaid",
                "insurance_id": "INS707707",
                "group_number": "GRP009",
                "date_of_service": date.today(),
                "plan_number": "PLAN009",
                "payer_phone": "555-222-1111",
                "payer_fax": "555-222-1112",
                "relationship": "Child",
            },
            {
                "first_name": "Olivia",
                "middle_name": "J",
                "last_name": "Clark",
                "birth_date": date(1993, 2, 14),
                "gender": "Female",
                "email": "olivia.c@example.com",
                "marital_status": "Married",
                "ssn": "808-66-8088",
                "address": "56 Aspen Way",
                "city": "Boston",
                "state": "MA",
                "zip_code": "02101",
                "phone": "555-123-7890",
                "language": "English",
                "ethnicity": "Caucasian",
                "insurance_type": "Private",
                "insurance_id": "INS808808",
                "group_number": "GRP010",
                "date_of_service": date.today(),
                "plan_number": "PLAN010",
                "payer_phone": "555-444-3333",
                "payer_fax": "555-444-3322",
                "relationship": "Parent",
            },
        ]

        for data in patients_data:
            patient, created = Patient.objects.get_or_create(
                ssn=data["ssn"],
                defaults={
                    **data,
                    "ref_physician": ref_physician,
                    "marital_status": data["marital_status"],
                    "service_type": service_type,
                },
            )
            status_msg = "Created" if created else "Already exists"
            self.stdout.write(
                self.style.SUCCESS(
                    f"{status_msg} patient: {patient.first_name} {patient.last_name}"
                )
            )
